// Extract the scrubbed FPV clip to a numbered WebP FRAME SEQUENCE (responsive
// tiers) so the scroll scrub paints decoded images instead of seeking an
// HTMLVideoElement. Seeking/playing a <video> per scroll frame is unreliable on
// iOS/WebKit (decode suspends for offscreen muted video, paused seeks are
// throughput-limited → the "church frame" freeze). An Image→texture upload is
// frame-accurate and rock-solid on every browser. This is the Apple-product-page
// technique (see the miso project).
//
// Requires ffmpeg (decode/scale) + cwebp (this machine's ffmpeg is webp
// DECODE-only, so we go video → PNG via ffmpeg, then PNG → WebP via cwebp).
//
//   node scripts/extract-frames.mjs [--in public/fpv.mp4] [--stride 2] [--q 80]
//
// --stride N keeps every Nth source frame (source is 25fps/589 frames; stride 2
// ⇒ ~295 frames ≈ 12.5fps, the "~300 frames" choice). Writes:
//   public/frames/<W>/0001.webp …            (one dir per tier width)
//   public/frames/manifest.json              { count, digits, ext, tiers:[…] }
// Tiers match VideoPlane's responsive source breakpoint (≤899.98px → mobile).

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

function arg(name, def) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const input = join(ROOT, arg("in", "media/fpv.mp4"));
const stride = Number(arg("stride", "2"));
const quality = Number(arg("q", "80"));
// width tiers (16:9 source → height = width*9/16). 1280 matches the current
// mobile video (fpv-720 is 1280×720); 1920 matches the desktop master.
const TIERS = [1280, 1920];
const DIGITS = 4;
const outRoot = join(ROOT, "public/frames");

console.log(`extract-frames: in=${input} stride=${stride} q=${quality} tiers=${TIERS.join(",")}`);

const tmp = mkdtempSync(join(tmpdir(), "dfrnc-frames-"));
try {
  // 1) video → full-res PNG, keeping every `stride`-th frame (deterministic, even).
  console.log("→ ffmpeg extracting PNG frames…");
  execFileSync(
    "ffmpeg",
    [
      "-hide_banner", "-loglevel", "error", "-y",
      "-i", input,
      "-vf", `select=not(mod(n\\,${stride}))`,
      "-vsync", "0",
      join(tmp, `f%0${DIGITS}d.png`),
    ],
    { stdio: "inherit" },
  );
  const pngs = readdirSync(tmp).filter((f) => f.endsWith(".png")).sort();
  const count = pngs.length;
  if (count === 0) throw new Error("no PNG frames extracted");
  console.log(`  extracted ${count} frames`);

  // 2) PNG → WebP per tier (cwebp resizes by width, height auto = -resize W 0).
  for (const w of TIERS) {
    const dir = join(outRoot, String(w));
    rmSync(dir, { recursive: true, force: true });
    mkdirSync(dir, { recursive: true });
    console.log(`→ cwebp tier ${w}px …`);
    pngs.forEach((p, i) => {
      const name = String(i + 1).padStart(DIGITS, "0"); // 1-indexed file names
      execFileSync("cwebp", [
        "-quiet", "-q", String(quality), "-resize", String(w), "0",
        join(tmp, p), "-o", join(dir, `${name}.webp`),
      ]);
    });
    console.log(`  tier ${w}px done (${count} frames)`);
  }

  // 3) manifest the runtime reads (frame count is data, not a hardcoded const).
  const manifest = { count, digits: DIGITS, ext: "webp", tiers: TIERS };
  writeFileSync(join(outRoot, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  // Bundled, type-safe copy imported by src/frames.ts (no resolveJsonModule needed).
  const ts =
    `// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.\n` +
    `// Describes the scrubbed FPV frame sequence under public/frames/<tier>/NNNN.webp.\n` +
    `export const FRAME_MANIFEST = {\n` +
    `  count: ${count},\n  digits: ${DIGITS},\n  ext: "webp",\n  tiers: [${TIERS.join(", ")}],\n} as const;\n`;
  writeFileSync(join(ROOT, "src/frameManifest.ts"), ts);
  console.log(`✓ wrote ${count} frames × ${TIERS.length} tiers + manifest.json + src/frameManifest.ts`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
