// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
// Describes the scrubbed FPV frame sequence under public/frames/<tier>/NNNN.webp.
export const FRAME_MANIFEST = {
  count: 295,
  digits: 4,
  ext: "webp",
  tiers: [1280, 1920],
} as const;
