// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
// Describes the scrubbed FPV frame sequence under public/frames/<tier>/NNNN.webp.
// sourceFps/stride record how the sequence was sampled from the master clip, so
// the runtime can derive the clip's NATIVE pace (sourceFps / stride) instead of
// hardcoding it — see src/frameScrub.ts.
export const FRAME_MANIFEST = {
  count: 295,
  digits: 4,
  ext: "webp",
  tiers: [1280, 1920],
  sourceFps: 25,
  stride: 2,
} as const;
